
template-file-path: cfn/packaged/root.yaml

parameters:
  ProjectName: todo-app
  BootstrapStackName: todo-app-bootstrap
  ContainerPort: 8080
  CacheTtlSeconds: 60
  ImageTag: latest
  TaskCpu: "512"
  TaskMemory: "1024"

tags:
  Project: todo-app
  Environment: lab
  ManagedBy: cloudformation-git-sync
